version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.21

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go mod download

      - run:
          name: Run tests
          command: go test -race ./...

workflows:
  version: 2
  verify:
    jobs:
      - test